import { ComponentDef } from "./types";

export const ComponentTypes: ComponentDef[] = [
    {
        name: "TextField",
        type: "TextField",
        title: "Text field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "MultilineTextField",
        type: "MultilineTextField",
        title: "Multiline text field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "YesNoField",
        type: "YesNoField",
        title: "Yes/No field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    // {
    //     name: "DateField",
    //     type: "DateField",
    //     title: "Date field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    // {
    //     name: "TimeField",
    //     type: "TimeField",
    //     title: "Time field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    // {
    //     name: "DateTimeField",
    //     type: "DateTimeField",
    //     title: "Date time field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    // {
    //     name: "DatePartsField",
    //     type: "DatePartsField",
    //     title: "Date parts field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    // {
    //     name: "DateTimePartsField",
    //     type: "DateTimePartsField",
    //     title: "Date time parts field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    // {
    //     name: "MonthYearField",
    //     type: "MonthYearField",
    //     title: "Month year field",
    //     subType: "field",
    //     hint: "",
    //     options: {},
    //     schema: {},
    // },
    {
        type: "DateAndTimeField",
        name: "DateAndTimeField",
        subType: "field",
        title: "date and time field-set",
        hint: "",
        options: {},
        date: {},
        addTime: false,
        schema: {},
    },
    {
        name: "SelectField",
        type: "SelectField",
        title: "Select field",
        subType: "field",
        options: {},
        schema: {},
        list: "",
    },
    {
        name: "AutocompleteField",
        type: "AutocompleteField",
        title: "Autocomplete field",
        subType: "field",
        options: {},
        schema: {},
        list: "",
    },
    {
        name: "RadiosField",
        type: "RadiosField",
        title: "Radios field",
        subType: "field",
        options: {},
        schema: {},
        list: "",
    },
    {
        name: "CheckboxesField",
        type: "CheckboxesField",
        title: "Checkboxes field",
        subType: "field",
        options: {},
        schema: {},
        list: "",
    },
    {
        name: "NumberField",
        type: "NumberField",
        title: "Number field",
        subType: "field",
        prefixType: "",
        prefixValue: "",
        suffixValue: "",
        precision: 0,
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "UkAddressField",
        type: "UkAddressField",
        title: "UK address field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "TelephoneNumberField",
        type: "TelephoneNumberField",
        title: "Telephone number field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "EmailAddressField",
        type: "EmailAddressField",
        title: "Email address field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "FileUploadField",
        type: "FileUploadField",
        title: "File upload field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
        addedFileTypes: [],
    },
    {
        name: "Para",
        type: "Para",
        title: "Paragraph",
        subType: "content",
        content: "",
        options: {},
        schema: {},
    },
    {
        name: "Result",
        type: "Result",
        title: "Result",
        subType: "content",
        // displayName: "Result",
        content: "",
        calculationName: "",
        expression: "",
        options: {},
        schema: {},
    },
    {
        name: "Html",
        type: "Html",
        title: "Html",
        subType: "content",
        content: "",
        options: {},
        schema: {},
    },
    {
        name: "InsetText",
        type: "InsetText",
        title: "Inset text",
        subType: "content",
        content: "",
        options: {},
        schema: {},
    },
    {
        name: "Details",
        type: "Details",
        title: "Details",
        subType: "content",
        content: "",
        options: {},
        schema: {},
    },
    // {
    //     name: "FlashCard",
    //     type: "FlashCard",
    //     title: "Flash card",
    //     subType: "content",
    //     options: {},
    //     schema: {},
    //     list: "",
    // },
    {
        name: "List",
        type: "List",
        title: "List",
        subType: "content",
        options: {},
        schema: {},
        list: "",
    },
    {
        name: "WebsiteField",
        type: "WebsiteField",
        title: "Website field",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "TableDataset",
        type: "TableDataset",
        title: "Table Data Set",
        subType: "content",
        content: "",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "Tabs",
        type: "Tabs",
        title: "Tabs Data Set",
        subType: "content",
        displayName: "Tabs Dataset",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "Filedownload",
        type: "Filedownload",
        title: "File download",
        selectedDocument: "",
        subType: "content",
        displayName: "File download",
        content: "",
        expression: "",
        options: {},
        schema: {},
    },

    {
        name: "DSIAccess",
        type: "DSIAccess",
        title: "DSI Access",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
    },
    {
        name: "DataImport",
        type: "DataImport",
        title: "Data Import",
        subType: "field",
        hint: "",
        options: {},
        schema: {},
        addedFileTypes: [],
        selectedDocument: "",
        documentName: "",
        columns: [],
        columnNames: [],
    },
];
