/**
 * Meta actions which do not affect a component's definition
 */
export enum Meta {
    NEW_COMPONENT = "NEW_COMPONENT",
    SET_COMPONENT = "SET_COMPONENT",
    SET_PAGE = "SET_PAGE",
    DELETE = "DELETE",
    VALIDATE = "VALIDATE",
    SET_SELECTED_LIST = "SET_SELECTED_LIST",
}

/**
 * actions which change the schema options
 */
export enum Schema {
    EDIT_SCHEMA_MIN = "EDIT_SCHEMA_MIN",
    EDIT_SCHEMA_MAX = "EDIT_SCHEMA_MAX",
    EDIT_SCHEMA_PRECISION = "EDIT_SCHEMA_PRECISION",
    EDIT_SCHEMA_LENGTH = "EDIT_SCHEMA_LENGTH",
    EDIT_SCHEMA_REGEX = "EDIT_SCHEMA_REGEX",
}

/**
 * actions which change the field options
 */
export enum Fields {
    EDIT_TITLE = "EDIT_TITLE",
    EDIT_NAME = "EDIT_NAME",
    EDIT_HELP = "EDIT_HELP",
    EDIT_CONTENT = "EDIT_CONTENT",
    EDIT_TYPE = "EDIT_TYPE",
    EDIT_DOCUMENT = "EDIT_DOCUMENT",
    DOCUMENT_NAME = "DOCUMENT_NAME",
    DOCUMENT_FIELDS = "DOCUMENT_FIELDS",
    SET_COLUMN_TYPE = "SET_COLUMN_TYPE",
    ADD_PREFIX_TYPE = "ADD_PREFIX_TYPE",
    ADD_PREFIX_VALUE = "ADD_PREFIX_VALUE",
    ADD_SUFFIX = "ADD_SUFFIX",
    ADD_CONDITION = "ADD_CONDITION",
    ADD_DISPLAY_NAME = "ADD_DISPLAY_NAME",
    ADD_CALCULATION = "ADD_CALCULATION",
    ADD_EXPRESSION = "ADD_EXPRESSION",
}

/**
 * actions which change the options
 */
export enum Options {
    EDIT_OPTIONS_HIDE_TITLE = "EDIT_OPTIONS_HIDE_TITLE",
    EDIT_OPTIONS_REQUIRED = "EDIT_OPTIONS_REQUIRED",
    EDIT_OPTIONS_HIDE_OPTIONAL = "EDIT_OPTIONS_HIDE_OPTIONAL",
    EDIT_OPTIONS_FILE_UPLOAD_MULTIPLE = "EDIT_OPTIONS_FILE_UPLOAD_MULTIPLE",
    EDIT_OPTIONS_CLASSES = "EDIT_OPTIONS_CLASSES",
    EDIT_OPTIONS_MAX_DAYS_IN_FUTURE = "EDIT_OPTIONS_MAX_DAYS_IN_FUTURE",
    EDIT_OPTIONS_MAX_DAYS_IN_PAST = "EDIT_OPTIONS_MAX_DAYS_IN_PAST",
    EDIT_DATA_IMPORT = "EDIT_DATA_IMPORT",
    EDIT_DELETE_COLUMN = "EDIT_DELETE_COLUMN",
    COLUMN_EDITED = "COLUMN_EDITED",
    COMPONENT_EDITED = "COMPONENT_EDITED",
    EDIT_OPTIONS_CONDITION = "EDIT_OPTIONS_CONDITION",
    EDIT_OPTIONS_TYPE = "EDIT_OPTIONS_TYPE",
    EDIT_OPTIONS_ROWS = "EDIT_OPTIONS_ROWS",
    EDIT_OPTIONS_AUTOCOMPLETE = "EDIT_OPTIONS_AUTOCOMPLETE",
    EDIT_OPTIONS_CUSTOM_MESSAGE = "EDIT_OPTIONS_CUSTOM_MESSAGE",
    EDIT_OPTIONS_LIST_FORMAT = "EDIT_OPTIONS_LIST_FORMAT",
    EDIT_OPTIONS_ADD_PREFIX_TYPE = "EDIT_OPTIONS_ADD_PREFIX_TYPE",
    EDIT_OPTIONS_ADD_PREFIX_VALUE = "EDIT_OPTIONS_ADD_PREFIX_VALUE",
    EDIT_OPTIONS_ADD_SUFFIX_TYPE = "EDIT_OPTIONS_ADD_SUFFIX_TYPE",
    EDIT_OPTIONS_ADD_SUFFIX = "EDIT_OPTIONS_ADD_SUFFIX",
    EDIT_OPTIONS_HIDE_RESULT = "EDIT_OPTIONS_HIDE_RESULT",
    EDIT_OPTIONS_HIDE_RESULT_ON_PAGE = "EDIT_OPTIONS_HIDE_RESULT_ON_PAGE",
    EDIT_OPTIONS_HIDE_RESULT_ON_SUMMARY = "EDIT_OPTIONS_HIDE_RESULT_ON_SUMMARY",
    EDIT_OPTIONS_BOLD = "EDIT_OPTIONS_BOLD",
}

export const Actions = {
    ...Meta,
    ...Schema,
    ...Fields,
    ...Options,
};
export type ComponentActions = typeof Actions;
